# This file was generated by GoReleaser. DO NOT EDIT.
cask "safe-install" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "c2bcc5f2d9e9f2a3dd7a20d59a726a6f9648ad51cc8698ccd2f00fae8ef67085"
      url "https://github.com/crossben/safe-install/releases/download/v#{version}/safe-install_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b7e99cf7d6c9a5399573ca52979222dbefd1a1375223fe71e0913a70a675b9d1"
      url "https://github.com/crossben/safe-install/releases/download/v#{version}/safe-install_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "55b78d4da135e3e3632c5a8578478c636c9030624b5cab522d2412af85be7531"
      url "https://github.com/crossben/safe-install/releases/download/v#{version}/safe-install_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b5a65c14182af27dc89fbc0ea1a31d70d54348b06168fd38104ea97e60b0ceb9"
      url "https://github.com/crossben/safe-install/releases/download/v#{version}/safe-install_linux_amd64.tar.gz"
    end
  end

  name "safe-install"
  desc "Install JavaScript dependencies without running install scripts you did not approve"
  homepage "https://github.com/crossben/safe-install"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "safe-install"

  # No zap stanza required

  caveats <<~EOS
    macOS may block the unsigned binary on first run. Remove the quarantine flag yourself:
      xattr -dr com.apple.quarantine "$(brew --caskroom)/safe-install"
  EOS
end
