# This file was generated by GoReleaser. DO NOT EDIT.
cask "safe-install" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "ab37a512c579f08a30e0b4f3da7637fbe2b58f5306c428f90ca6270ebbbaa6ff"
      url "https://github.com/crossben/safe-install/releases/download/v#{version}/safe-install_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "edf4351f8a0b343b021626f29dd4474951cb51451d23057654b84e3cc6c07d87"
      url "https://github.com/crossben/safe-install/releases/download/v#{version}/safe-install_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bdfbf9ebb17349db100ea289d0f3f3e6d49344bddc5e3e3eb776c5752ef38be4"
      url "https://github.com/crossben/safe-install/releases/download/v#{version}/safe-install_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5e1b3a507f7b2fb622bfd40cf1f46f41a507775d155396f730ae73c4b064cf62"
      url "https://github.com/crossben/safe-install/releases/download/v#{version}/safe-install_linux_amd64.tar.gz"
    end
  end

  name "safe-install"
  desc "Install JavaScript dependencies without running install scripts you did not approve"
  homepage "https://github.com/crossben/safe-install"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "safe-install"

  # No zap stanza required

  caveats <<~EOS
    macOS may block the unsigned binary on first run. Remove the quarantine flag yourself:
      xattr -dr com.apple.quarantine "$(brew --caskroom)/safe-install"
  EOS
end
