# This file was generated by GoReleaser. DO NOT EDIT.
cask "safe-install" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "794ed3b4241a58a0d59a0d9f318a86896fa8b4894d3fd14e5114cc7d91f250b0"
      url "https://github.com/crossben/safe-install/releases/download/v#{version}/safe-install_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f0e9b834381e739eed75cac80a824e4b5873a4a4a2aab0fadeee68d9df8e626a"
      url "https://github.com/crossben/safe-install/releases/download/v#{version}/safe-install_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "89dd4704e31ce628a199a5341239d38e185613a6248d6b8c9a891fdfc7568e14"
      url "https://github.com/crossben/safe-install/releases/download/v#{version}/safe-install_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "792f2a6faf5a9759f3185178bab6388c658e741226e9ed7f4092b032668b7530"
      url "https://github.com/crossben/safe-install/releases/download/v#{version}/safe-install_linux_amd64.tar.gz"
    end
  end

  name "safe-install"
  desc "Install JavaScript dependencies without running install scripts you did not approve"
  homepage "https://github.com/crossben/safe-install"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "safe-install"

  # No zap stanza required

  caveats <<~EOS
    macOS may block the unsigned binary on first run. Remove the quarantine flag yourself:
      xattr -dr com.apple.quarantine "$(brew --caskroom)/safe-install"
  EOS
end
